/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.awt.Color;
import javax.swing.UIDefaults;


/**
 *
 * @author lahcen
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        bar7 = new javax.swing.JProgressBar();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        bar = new javax.swing.JProgressBar();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        bar1 = new javax.swing.JProgressBar();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        bar2 = new javax.swing.JProgressBar();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        bar3 = new javax.swing.JProgressBar();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        bar4 = new javax.swing.JProgressBar();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        bar5 = new javax.swing.JProgressBar();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        bar6 = new javax.swing.JProgressBar();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(242, 242, 240));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 94, 58));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("USEO");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 13, -1, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 15, 20, 20));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 50));

        jLabel63.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(204, 204, 204));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel63.setText("Genre");
        jPanel2.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 170, 70, 20));

        jLabel64.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(38, 46, 79));
        jLabel64.setText("PROFILE");
        jLabel64.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 80, 20));

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profile.png"))); // NOI18N
        jPanel2.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 110, 20, 20));

        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(38, 46, 79));
        jLabel66.setText("MY MUSIC");
        jLabel66.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 80, 20));

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/music.png"))); // NOI18N
        jPanel2.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 140, 20, 20));

        jLabel68.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(204, 204, 204));
        jLabel68.setText("Navigation");
        jPanel2.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 75, -1, -1));

        jLabel69.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(204, 204, 204));
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel69.setText("Collection");
        jPanel2.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 200, 70, 20));

        jLabel70.setBackground(new java.awt.Color(243, 227, 221));
        jLabel70.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 94, 58));
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("Alphebetical");
        jLabel70.setOpaque(true);
        jPanel2.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 90, 20));

        jLabel71.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(204, 204, 204));
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel71.setText("Collection");
        jPanel2.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 260, 70, 20));

        jLabel72.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(38, 46, 79));
        jLabel72.setText("COLLECTION");
        jLabel72.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 80, 20));

        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/collection.png"))); // NOI18N
        jPanel2.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 290, 20, 20));

        jLabel74.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(38, 46, 79));
        jLabel74.setText("FAVORITES");
        jLabel74.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 80, 20));

        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/favorites.png"))); // NOI18N
        jPanel2.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 320, 20, 20));

        jLabel76.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(38, 46, 79));
        jLabel76.setText("RANDOM");
        jLabel76.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 80, 20));

        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/random.png"))); // NOI18N
        jPanel2.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 350, 20, 20));

        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left.png"))); // NOI18N
        jPanel2.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 5, 90));

        jLabel79.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(204, 204, 204));
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel79.setText("_");
        jPanel2.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 166, 15, 15));

        jLabel80.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(204, 204, 204));
        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel80.setText("_");
        jPanel2.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 197, 15, 15));

        jLabel81.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(204, 204, 204));
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel81.setText("_");
        jPanel2.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 255, 15, 15));

        jLabel85.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(204, 204, 204));
        jLabel85.setText("Friends");
        jPanel2.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 390, -1, -1));

        jLabel86.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/friend1.png"))); // NOI18N
        jPanel2.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 415, 20, 20));

        jLabel87.setForeground(new java.awt.Color(153, 153, 153));
        jLabel87.setText("Vincent T.");
        jPanel2.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 415, -1, 20));

        jLabel88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/friend2.png"))); // NOI18N
        jPanel2.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 20, 20));

        jLabel89.setForeground(new java.awt.Color(153, 153, 153));
        jLabel89.setText("Anne T.");
        jPanel2.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 440, -1, 20));

        jLabel90.setForeground(new java.awt.Color(153, 153, 153));
        jLabel90.setText("Tommy R.");
        jPanel2.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 465, -1, 20));

        jLabel91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/friend3.png"))); // NOI18N
        jPanel2.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 465, 20, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 520));

        jPanel4.setBackground(new java.awt.Color(38, 46, 79));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(19, 27, 60));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(109, 118, 154));
        jLabel37.setText("RELATED");
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 15, 70, 20));

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/settings.png"))); // NOI18N
        jPanel5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 20, 20));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 50));

        jPanel6.setBackground(new java.awt.Color(19, 27, 60));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel82.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(109, 118, 154));
        jLabel82.setText("Space");
        jPanel6.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 12, -1, -1));

        bar7.setBackground(new java.awt.Color(204, 204, 204));
        bar7.setForeground(new java.awt.Color(99, 171, 243));
        bar7.setMinimum(30);
        bar7.setValue(65);
        bar7.setString("");
        bar7.setStringPainted(true);
        UIDefaults defaults10 = new UIDefaults();
        defaults10.put("ProgressBar[Enabled].foregroundPainter", new MyPainter(Color.decode("#63abf3")));
        defaults10.put("ProgressBar[Enabled+Finished].foregroundPainter", new MyPainter(Color.decode("#63abf3")));

        bar7.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
        bar7.putClientProperty("Nimbus.Overrides", defaults10);
        jPanel6.add(bar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, 10));

        jLabel83.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(204, 204, 204));
        jLabel83.setText("HDD");
        jPanel6.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel84.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(204, 204, 204));
        jLabel84.setText("300 Go");
        jPanel6.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 12, -1, -1));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 140, 50));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/effect.png"))); // NOI18N
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 140, 80));

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar.setBackground(new java.awt.Color(204, 204, 204));
        bar.setForeground(new java.awt.Color(74, 75, 176));
        bar.setMinimum(30);
        bar.setValue(60);
        bar.setString("");
        bar.setStringPainted(true);
        UIDefaults defaults = new UIDefaults();
        defaults.put("ProgressBar[Enabled].foregroundPainter", new MyPainter(Color.decode("#4a4bb0")));
        defaults.put("ProgressBar[Enabled+Finished].foregroundPainter", new MyPainter(Color.decode("#4a4bb0")));

        bar.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
        bar.putClientProperty("Nimbus.Overrides", defaults);
        jPanel8.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 100, 10));

        jLabel40.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 204, 204));
        jLabel40.setText("Shigeto");
        jPanel8.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jLabel41.setText("jLabel41");
        jPanel8.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 17, 15, 15));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 40));

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar1.setBackground(new java.awt.Color(204, 204, 204));
        bar1.setForeground(new java.awt.Color(74, 75, 176));
        bar1.setMinimum(30);
        bar1.setValue(90);
        bar1.setString("");
        bar1.setStringPainted(true);
        UIDefaults defaults1 = new UIDefaults();
        defaults1.put("ProgressBar[Enabled].foregroundPainter", new MyPainter(Color.decode("#4a4bb0")));
        defaults1.put("ProgressBar[Enabled+Finished].foregroundPainter", new MyPainter(Color.decode("#4a4bb0")));

        bar1.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
        bar1.putClientProperty("Nimbus.Overrides", defaults1);
        jPanel9.add(bar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 100, 10));

        jLabel42.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 204, 204));
        jLabel42.setText("Com Truise");
        jPanel9.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jLabel43.setText("jLabel41");
        jPanel9.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 17, 15, 15));

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 120, 40));

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar2.setBackground(new java.awt.Color(204, 204, 204));
        bar2.setForeground(new java.awt.Color(74, 75, 176));
        bar2.setMinimum(30);
        bar2.setValue(40);
        bar2.setString("");
        bar2.setStringPainted(true);
        UIDefaults defaults3 = new UIDefaults();
        defaults3.put("ProgressBar[Enabled].foregroundPainter", new MyPainter(Color.decode("#4a4bb0")));
        defaults3.put("ProgressBar[Enabled+Finished].foregroundPainter", new MyPainter(Color.decode("#4a4bb0")));

        bar2.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
        bar2.putClientProperty("Nimbus.Overrides", defaults3);
        jPanel10.add(bar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 100, 10));

        jLabel44.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(204, 204, 204));
        jLabel44.setText("Thomas Azier");
        jPanel10.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jLabel45.setText("jLabel41");
        jPanel10.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 17, 15, 15));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 40));

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar3.setBackground(new java.awt.Color(204, 204, 204));
        bar3.setForeground(new java.awt.Color(74, 75, 176));
        bar3.setMinimum(30);
        bar3.setValue(75);
        bar3.setString("");
        bar3.setStringPainted(true);
        UIDefaults defaults4 = new UIDefaults();
        defaults4.put("ProgressBar[Enabled].foregroundPainter", new MyPainter(Color.decode("#4a4bb0")));
        defaults4.put("ProgressBar[Enabled+Finished].foregroundPainter", new MyPainter(Color.decode("#4a4bb0")));

        bar3.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
        bar3.putClientProperty("Nimbus.Overrides", defaults4);
        jPanel11.add(bar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 100, 10));

        jLabel46.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(204, 204, 204));
        jLabel46.setText("Royksopp");
        jPanel11.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jLabel47.setText("jLabel41");
        jPanel11.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 17, 15, 15));

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 120, 40));

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar4.setBackground(new java.awt.Color(204, 204, 204));
        bar4.setForeground(new java.awt.Color(99, 171, 243));
        bar4.setMinimum(30);
        bar4.setValue(100);
        bar4.setString("");
        bar4.setStringPainted(true);
        UIDefaults defaults5 = new UIDefaults();
        defaults5.put("ProgressBar[Enabled].foregroundPainter", new MyPainter(Color.decode("#63abf3")));
        defaults5.put("ProgressBar[Enabled+Finished].foregroundPainter", new MyPainter(Color.decode("#63abf3")));

        bar4.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
        bar4.putClientProperty("Nimbus.Overrides", defaults5);
        jPanel12.add(bar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 100, 10));

        jLabel48.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(204, 204, 204));
        jLabel48.setText("Lorde");
        jPanel12.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jLabel49.setText("jLabel41");
        jPanel12.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 17, 15, 15));

        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 120, 40));

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar5.setBackground(new java.awt.Color(204, 204, 204));
        bar5.setForeground(new java.awt.Color(74, 75, 176));
        bar5.setMinimum(30);
        bar5.setValue(50);
        bar5.setString("");
        bar5.setStringPainted(true);
        UIDefaults defaults6 = new UIDefaults();
        defaults6.put("ProgressBar[Enabled].foregroundPainter", new MyPainter(Color.decode("#4a4bb0")));
        defaults6.put("ProgressBar[Enabled+Finished].foregroundPainter", new MyPainter(Color.decode("#4a4bb0")));

        bar5.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
        bar5.putClientProperty("Nimbus.Overrides", defaults6);
        jPanel13.add(bar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 100, 10));

        jLabel50.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(204, 204, 204));
        jLabel50.setText("JMSN");
        jPanel13.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jLabel51.setText("jLabel41");
        jPanel13.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 17, 15, 15));

        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 120, 40));

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar6.setBackground(new java.awt.Color(204, 204, 204));
        bar6.setForeground(new java.awt.Color(74, 75, 176));
        bar6.setMinimum(30);
        bar6.setValue(75);
        bar6.setString("");
        bar6.setStringPainted(true);
        UIDefaults defaults7 = new UIDefaults();
        defaults7.put("ProgressBar[Enabled].foregroundPainter", new MyPainter(Color.decode("#4a4bb0")));
        defaults7.put("ProgressBar[Enabled+Finished].foregroundPainter", new MyPainter(Color.decode("#4a4bb0")));

        bar6.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
        bar6.putClientProperty("Nimbus.Overrides", defaults7);
        jPanel14.add(bar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 100, 10));

        jLabel52.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(204, 204, 204));
        jLabel52.setText("Woodkid");
        jPanel14.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jLabel53.setText("jLabel41");
        jPanel14.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 17, 15, 15));

        jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 120, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 140, 520));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 240));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/download.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 155, 100, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("2017");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 125, 210, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("No Better Time Than Now");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 210, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SHIGETO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 75, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/slider.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 540, 150));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("0");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 20, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("9");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 20, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("A");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 20, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("B");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 20, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("C");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 20, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("D");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 20, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("E");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 20, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("f");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 20, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("J");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 20, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("K");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 20, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("L");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 20, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("M");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 20, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("N");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 20, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("O");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 20, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("P");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 20, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Q");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 20, 20));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("R");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 20, 20));

        jLabel25.setBackground(new java.awt.Color(255, 239, 235));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 94, 58));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("S");
        jLabel25.setOpaque(true);
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 20, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("T");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 20, 20));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("U");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 20, 20));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 204, 204));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("V");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 20, 20));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 204));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("W");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 20, 20));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 204, 204));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("X");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 20, 20));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 204, 204));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Y");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 20, 20));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 204, 204));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Z");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 20, 20));

        jLabel33.setBackground(new java.awt.Color(204, 204, 204));
        jLabel33.setOpaque(true);
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, 340, 1));

        jLabel34.setBackground(new java.awt.Color(255, 94, 58));
        jLabel34.setOpaque(true);
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 35, 20, 1));

        jLabel35.setBackground(new java.awt.Color(204, 204, 204));
        jLabel35.setOpaque(true);
        jPanel7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 35, 140, 1));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/002.png"))); // NOI18N
        jPanel7.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 110, 110));

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/005.png"))); // NOI18N
        jPanel7.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 110, 110));

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/001.png"))); // NOI18N
        jPanel7.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 110));

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/003.png"))); // NOI18N
        jPanel7.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 110, 110));

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/004.png"))); // NOI18N
        jPanel7.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 110, 110));

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/006.png"))); // NOI18N
        jPanel7.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 110, 110));

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/007.png"))); // NOI18N
        jPanel7.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 110, 110));

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/008.png"))); // NOI18N
        jPanel7.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 110, 110));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 540, 320));

        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Search");
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 13, 110, 23));

        jLabel36.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(153, 153, 153));
        jLabel36.setText("<html>\n<head>\n<style>\nspan{\n   font-weight:bold;\n   font-size:12px;\n   color:#262e4f;\n}\n</style>\n</head>\n<body>\n<p><span>SHIGETO</span>  Detroit - USA</p>\n</body>\n</html>");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 300, 30));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/text.png"))); // NOI18N
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 12, 150, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar;
    private javax.swing.JProgressBar bar1;
    private javax.swing.JProgressBar bar2;
    private javax.swing.JProgressBar bar3;
    private javax.swing.JProgressBar bar4;
    private javax.swing.JProgressBar bar5;
    private javax.swing.JProgressBar bar6;
    private javax.swing.JProgressBar bar7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
